name: Release

on:
  push:
  workflow_dispatch:
    inputs:
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
      github-release:
        required: false
        type: boolean
        default: false
        description: "Publish Github release for the current version"
  # Monitor pull request events
  pull_request:
    types:
      - closed
  # 'develop' is for testing only, change this value to 'main' before merging to main
    branches:
      - develop

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # change this value to 'main' before merging to 'main', this value should be the same as 'on->pull_request->branches'
          develop-branch: develop
          version-files: composer.json
          release-title: Adyen Magento-2 Plugin
          pre-release: ${{ inputs.pre-release || false }}
          github-release: ${{ inputs.github-release || true }}
          separator: .pre.beta
