name: Release

on:
  push:

  # Manual run from Github UI (e.g. for when a merged PR labels have changed)
  workflow_dispatch:
    inputs:
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
        # Publish the current version now, useful if the automated run failed
      github-release:
        required: false
        type: boolean
        default: false
        description: "Publish Github release for the current version"
  # Monitor pull request events

  pull_request:
    types:
      - closed
  # TODO: 'develop' is for testing only, change this value to 'main' before merging to main
    branches:
      - develop

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
#     TODO: Remove after finalising
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug
        run: |
          ls -la
          cat VERSION

      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: change this value to 'main' before merging to 'main', this value should be the same as 'on->pull_request->branches'
          develop-branch: develop
          version-files: composer.json
          release-title: Adyen Magento-2 Plugin
          pre-release: ${{ inputs.pre-release || false }}
          # For a manual Github release
          github-release: ${{ inputs.github-release || false }}
          separator: .pre.beta

