name: E2E Tests
run-name: Headless E2E test run triggered by adyen-integration-tools-tests ${{inputs.testBranch}}

on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Test Branch from Integration Tools Repo"
        required: true
        default: "develop"

jobs:
  e2e:
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    container: cenkiravul/docker-magento:2.4.5-p1

    services:
      mariadb:
        image: mariadb:10.4
      elasticsearch:
        image: elasticsearch:7.16.2
      playwright:
        image: mcr.microsoft.com/playwright:focal

    steps:
      - name: run tests
        run: cd /tmp;
          git clone https://github.com/Adyen/adyen-integration-tools-tests.git;
          cd adyen-integration-tools-tests;
          git checkout $INTEGRATION_TESTS_BRANCH;
          npm run test:ci:magento
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       PHP_VERSION: "8.1"
#       MAGENTO_VERSION: "2.4.5"
#       ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
#       ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install Magento
#         run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm web make magento

#       - name: Start web server in background
#         run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d web
#         env:
#           DONATION_ACCOUNT: ${{secrets.DONATION_ACCOUNT}}
#           ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}
#           ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
#           ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}

#       - name: Setup permissions
#         run: docker exec magento2-container make fs

#       - name: Check install
#         run: docker exec magento2-container make sys-check

#       - name: Install plugin
#         run: docker exec -u www-data magento2-container make plugin

#       - name: Switch to production mode
#         run: docker exec -u www-data magento2-container make production

#       - name: Setup permissions
#         run: docker exec magento2-container make fs

#       - name: Run E2E tests
#         run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm playwright /e2e.sh
#         env:
#           INTEGRATION_TESTS_BRANCH: ${{inputs.testBranch}}
#           MAGENTO_ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
#           MAGENTO_ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
#           MAGENTO_BASE_URL: ${{secrets.MAGENTO_BASE_URL}}
#           PAYPAL_USERNAME: ${{secrets.PLAYWRIGHT_PAYPAL_USERNAME}}
#           PAYPAL_PASSWORD: ${{secrets.PLAYWRIGHT_PAYPAL_PASSWORD}}
#           ADYEN_API_KEY : ${{secrets.ADYEN_API_KEY}}
#           ADYEN_CLIENT_KEY : ${{secrets.ADYEN_CLIENT_KEY}}
#           ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}

#       - name: Archive test result artifacts
#         if: always()
#         uses: actions/upload-artifact@v3
#         with:
#           name: html-report
#           path: test-report
