name: Integration Tests
on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: 7.4
            MAGENTO_VERSION: 2.4.2
    runs-on: ubuntu-latest
    env:
      ADMIN_USERNAME: ${{ secrets.MAGENTO_ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.MAGENTO_ADMIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Magento
        run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm web make magento

      - name: Start web server in background
        run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d web
        env:
          ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}
          ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
          ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}

      - name: Setup permissions
        run: docker exec magento2-container make fs

      - name: Check install
        run: docker exec magento2-container make sys-check

      - name: Install plugin
        run: docker exec -u www-data magento2-container make plugin

      - run: docker exec magento2-container /etc/init.d/cron stop

      - name: Run unit tests
        run: docker exec -u www-data magento2-container make unit

      - name: Run GraphQL tests
        continue-on-error: true
        run: docker exec magento2-container make graphql

      - name: Switch to production mode
        run: docker exec -u www-data magento2-container make production
      - name: Configure the plugin
        run: |
          docker exec magento2-container bin/magento config:set payment/adyen_abstract/demo_mode 1
          docker exec magento2-container bin/magento config:set payment/adyen_hpp/active 1
          docker exec magento2-container bin/magento config:set payment/adyen_cc/active 1
          docker exec magento2-container bin/magento config:set payment/adyen_abstract/merchant_account "${{secrets.ADYEN_MERCHANT}}"
          docker exec magento2-container ./n98-magerun2.phar config:store:set --encrypt payment/adyen_abstract/api_key_test "${{secrets.ADYEN_API_KEY}}" > /dev/null

      - name: Setup permissions
        run: docker exec magento2-container make fs

      - name: Run E2E tests
        continue-on-error: true
        run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm playwright /e2e.sh
        env:
          INTEGRATION_TESTS_BRANCH: develop
          MAGENTO_BASE_URL: ${{secrets.MAGENTO_BASE_URL}}
          PAYPAL_USERNAME: ${{secrets.PLAYWRIGHT_PAYPAL_USERNAME}}
          PAYPAL_PASSWORD: ${{secrets.PLAYWRIGHT_PAYPAL_PASSWORD}}

      - name: Archive test result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: test-report
