name: Main CI workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.1]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v1
        coverage: xdebug
    - name: Test plugin installation
      run: |
        echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
        composer install --prefer-dist
      env:
        CI: true
        MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
        MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}
    - name: Code Sniffer
      run: vendor/bin/phpcs --extensions=php,phtml --error-severity=10 --ignore-annotations

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-clover build/clover.xml Test/Unit

    # PHPUnit generates absolute file paths and SonarCloud expects relative file paths. This command removes the
    # current working directory from the report files.
    - name: Clean up code coverage reports
      run: sed -i "s;`pwd`/;;g" build/clover.xml

    - name: Fix code coverage paths
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' clover.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
