name: Main CI workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [8.1]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2

    - name: Test plugin installation
      run: |
        echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME_V2}\",\"password\":\"${MAGENTO_PASSWORD_V2}\"}}}" > auth.json
        composer install --prefer-dist
      env:
        CI: true
        MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
        MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}

    - name: Code Sniffer
      run: vendor/bin/phpcs --extensions=php,phtml --error-severity=10 --ignore-annotations

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-clover=build/clover.xml --log-junit=build/tests-log.xml -c Test/phpunit.xml Test/Unit

    - name: Fix code coverage paths
      run: sed -i "s;`pwd`/;;g" build/*.xml

    - name: SonarCloud Scan
      if: ${{ env.SONAR_TOKEN }}
      uses: SonarSource/sonarcloud-github-action@master
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
