name: Functional Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository)
    environment: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) && 'external' || 'internal' }}
    strategy:
      matrix:
        include:
          - php-version: '8.3'
            magento-version: '2.4.7-p2'
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      MAGENTO_VERSION: ${{ matrix.magento-version }}
      ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
      ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
      DONATION_ACCOUNT: ${{secrets.DONATION_ACCOUNT}}
      ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}
      ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
      ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}
      DEPLOY_SAMPLEDATA: 1

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Start services
        run: docker compose -f .github/docker-compose.yml -f .github/docker-compose.mftf.yml up -d

      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash

      - name: Setup Magento
        run: docker-compose -f .github/docker-compose.yml -f .github/docker-compose.mftf.yml exec -T web make magento

      - name: Install plugin
        run: docker exec -u www-data magento2-container make plugin

      - run: docker exec magento2-container /etc/init.d/cron stop

      - name: Build MFTF project
        run: docker exec magento2-container make setup-mftf

      - name: Run MFTF tests
        run: docker exec magento2-container make mftf

