name: PHPStan analysis

on:
  pull_request:
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) || (github.event_name == 'workflow_dispatch')
    environment: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) && 'external' || 'internal' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2,8.3]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Test plugin installation
        run: |
          echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
          composer install --prefer-dist
        env:
          CI: true
          MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
          MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}

      - name: Install Magento PHPStan dependecies
        run: |
          composer require --dev bitexpert/phpstan-magento
          composer config allow-plugins.phpstan/extension-installer true
          composer require --dev phpstan/extension-installer

      - name: PHPStan
        run: vendor/bin/phpstan analyse . -c phpstan.neon
