name: Integration Test Repository Pipeline
run-name: Headless E2E test run triggered by adyen-integration-tools-tests ${{inputs.testBranch}}

on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Integration Test Repository Pipeline"
        required: true
        default: "develop"

jobs:
  build:
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    container:
      image: ataberkylmz/magento2
    env:
      PHP_VERSION: "8.1"
      MAGENTO_VERSION: "2.4.5"
      ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
      ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
      DB_SERVER: mariadb
      ELASTICSEARCH_SERVER: elasticsearch
      MAGENTO_HOST: magento2.test.com
      VIRTUAL_HOST: magento2.test.com
      COMPOSER_MEMORY_LIMIT: -1
      DEPLOY_SAMPLEDATA: 1
    ports:
      - 80, 443
    volumes:
      - magento:/var/www/html
      - composer:/usr/local/bin
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MARIADB_ROOT_PASSWORD: root_password
          MARIADB_DATABASE: magento
          MARIADB_USER: magento
          MARIADB_PASSWORD: magento
        volumes:
          - sqldata:/var/lib/mysql
          - sqlsocket:/var/run/msqld

      elasticsearch:
        image: elasticsearch:7.16.2
        ports:
          - 9200:9200
          - 9300:9300
        env:
          "discovery.type=single-node"
          ES_JAVA_OPTS=-Xms750m -Xmx750m

    steps:
      - uses: actions/checkout@v2

      - name: Install plugin
        run: docker exec -u www-data magento2-container make plugin

      - name: Switch to production mode
        run: docker exec -u www-data magento2-container make production

      - name: Setup permissions
        run: docker exec magento2-container make fs

      - name: Run E2E tests
        run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm playwright /e2e.sh
        env:
          INTEGRATION_TESTS_BRANCH: ${{inputs.testBranch}}
          MAGENTO_ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
          MAGENTO_ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
          MAGENTO_BASE_URL: ${{secrets.MAGENTO_BASE_URL}}
          PAYPAL_USERNAME: ${{secrets.PLAYWRIGHT_PAYPAL_USERNAME}}
          PAYPAL_PASSWORD: ${{secrets.PLAYWRIGHT_PAYPAL_PASSWORD}}
          ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
          ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}
          ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}

      - name: Archive test result artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: test-report
