name: Integration Test Repository Pipeline
run-name: Headless E2E tests - Full Coverage - Test Repo Branch ${{inputs.testBranch}} with Express Checkout ${{inputs.expressBranch}}

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Integration Test Repository Pipeline"
        required: true
        default: "develop"
      expressBranch:
        description: "Express Checkout Repository Pipeline"
        required: true
        default: "develop"

jobs:
  build:
    if: ${{ github.actor != 'renovate[bot]' || github.actor != 'lgtm-com[bot]' }}
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    timeout-minutes: 20
    env:
      PHP_VERSION: "8.1"
      MAGENTO_VERSION: "2.4.5"
      ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
      ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
    steps:
      - uses: actions/checkout@v3

      - name: Install Magento
        run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm web make magento

      - name: Start web server in background
        run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d web
        env:
          DONATION_ACCOUNT: ${{secrets.DONATION_ACCOUNT}}
          ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}
          ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
          ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}

      - name: Setup permissions
        run: docker exec magento2-container make fs

      - name: Check install
        run: docker exec magento2-container make sys-check

      - name: Install plugin
        run: docker exec -u www-data magento2-container make plugin

      - name: Install Express module
        run: docker exec -u www-data magento2-container composer require adyen/adyen-magento2-expresscheckout:dev-${{inputs.expressBranch}}

      - name: Enable Express module
        run: docker exec -u www-data magento2-container make enable-express

      - name: Switch to production mode
        run: docker exec -u www-data magento2-container make production

      - name: Setup permissions
        run: docker exec magento2-container make fs

      - name: Run E2E tests
        run: docker-compose -f .github/workflows/templates/docker-compose.yml run --rm playwright /e2e-all.sh
        env:
          INTEGRATION_TESTS_BRANCH: ${{inputs.testBranch}}
          MAGENTO_ADMIN_USERNAME: ${{secrets.MAGENTO_ADMIN_USERNAME}}
          MAGENTO_ADMIN_PASSWORD: ${{secrets.MAGENTO_ADMIN_PASSWORD}}
          MAGENTO_BASE_URL: ${{secrets.MAGENTO_BASE_URL}}
          PAYPAL_USERNAME: ${{secrets.PLAYWRIGHT_PAYPAL_USERNAME}}
          PAYPAL_PASSWORD: ${{secrets.PLAYWRIGHT_PAYPAL_PASSWORD}}
          ADYEN_API_KEY: ${{secrets.ADYEN_API_KEY}}
          ADYEN_CLIENT_KEY: ${{secrets.ADYEN_CLIENT_KEY}}
          ADYEN_MERCHANT: ${{secrets.ADYEN_MERCHANT}}
          GOOGLE_USERNAME: ${{secrets.GOOGLE_USERNAME}}
          GOOGLE_PASSWORD: ${{secrets.GOOGLE_PASSWORD}}

      - name: Archive test result artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: test-report
